Repository wecode-bootcamp-korea/37-2nd-skyski-backend, pull requests merged in 2022-10, with the labels that each got.

#1 초기 세팅
  .env.sample
  .gitignore
  app.js
  package-lock.json
  package.json
  src/controllers/index.js
  src/middlewares/index.js
  src/models/dataSource.js
  src/models/index.js
  src/routes/index.js
  src/services/index.js
  src/utils/index.js
Labels: 완료

#2 DB 모델링
  db/migrations/20221004122435_create_regions_table.sql
  db/migrations/20221004122645_create_airports_table.sql
  db/migrations/20221004122735_create_users_table.sql
  db/migrations/20221004122802_create_hotels_table.sql
  db/migrations/20221004122821_create_agencies_table.sql
  db/migrations/20221004122845_create_products_table.sql
  db/migrations/20221004122859_create_airlines_table.sql
  db/migrations/20221004122914_create_orders_table.sql
  db/migrations/20221004122927_create_flights_table.sql
  db/migrations/20221004122938_create_flight_products_table.sql
Labels: 완료

#4 DB 순서 변경
  db/migrations/20221004122934_create_orders_table.sql
Labels: 완료

#6 데이터 베이스 테이블 수정
  .env.sample
  .gitignore
  db/migrations/20221004122927_create_flights_table.sql
Labels: 완료

#8 db 테이블 수정
  db/migrations/20221004122802_create_hotels_table.sql
Labels: 멘토 리뷰 요청

#12 [MODIFY] 소셜 로그인 기능 수정 구현
  package-lock.json
  src/models/dataSource.js
  src/models/index.js
  src/models/userDao.js
  src/services/userService.js
Labels: 완료

#9 Feature/search
  db/migrations/20221004122435_create_regions_table.sql
  db/migrations/20221004122934_create_orders_table.sql
  package-lock.json
  src/controllers/flightController.js
  src/controllers/index.js
  src/models/flightDao.js
  src/models/index.js
  src/routes/flightRouter.js
  src/routes/index.js
  src/services/flightService.js
  src/services/index.js
  src/utils/error.js
  src/utils/index.js
Labels: 수정 요청
